; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:ISP_fuses]
platform = atmelavr
board = ATmega328P
upload_protocol = custom
upload_command = avrdude.exe $UPLOAD_FLAGS
upload_flags =
	-pm328pb
	-B10
	-Cavrdude.conf
	-cusbasp
	-PUSB
	-Ulfuse:w:0xEF:m
	-Uhfuse:w:0xDF:m
	-Uefuse:w:0xF7:m
	-Uflash:w:$PROG_PATH:e
	-v

[env:ISP]
platform = atmelavr
board = ATmega328P
upload_protocol = custom
upload_command = avrdude.exe $UPLOAD_FLAGS
upload_flags =
	-pm328pb
	-B10
	-Cavrdude.conf
	-cusbasp
	-PUSB
	-Uflash:w:$PROG_PATH:e
	-v

[env:burn_bootloader]
platform = atmelavr
board = ATmega328P
upload_protocol = custom
upload_command = avrdude.exe $UPLOAD_FLAGS
upload_flags =
	-pm328pb
	-B10
	-Cavrdude.conf
	-cusbasp
	-PUSB
	-Uflash:w:$PROJECT_DIR/optiboot/optiboot_atmega328.hex:i
	-v

[env:burn_bootloader_fuses]
platform = atmelavr
board = ATmega328P
upload_protocol = custom
upload_command = avrdude.exe $UPLOAD_FLAGS
upload_flags =
	-pm328pb
	-B10
	-Cavrdude.conf
	-cusbasp
	-PUSB
	-Ulfuse:w:0xEF:m
	-Uhfuse:w:0xDF:m
	-Uefuse:w:0xF7:m
	-Uflash:w:optiboot/optiboot_atmega328.hex:i
	-v

[env:optiboot]
platform = atmelavr
board = ATmega328P
upload_protocol = custom
upload_command = avrdude.exe $UPLOAD_FLAGS
upload_flags =
	-pm328p
	-Cavrdude.conf
	-carduino
	-PCOM4
	-Uflash:w:$PROG_PATH:e
	-v