; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:USBTiny_fuses_win]
platform_packages = tool_avrdude@symlink://C:/Users/marti/avrdude
platform = atmelavr
board = ATmega328P
upload_protocol = custom
upload_command = avrdude $UPLOAD_FLAGS
upload_flags =
	-pm328pb
	-B10
	-Cavrdude.conf
	-cusbtiny
	-Ulfuse:w:0xEF:m
	-Uhfuse:w:0xDF:m
	-Uefuse:w:0xF7:m
	-Uflash:w:$PROG_PATH:e
	-v

[env:USBTiny_win]
platform_packages = tool_avrdude@symlink://C:/Users/marti/avrdude
platform = atmelavr
board = ATmega328P
upload_protocol = custom
upload_command = avrdude $UPLOAD_FLAGS
upload_flags =
	-pm328pb
	-B10
	-Cavrdude.conf
	-cusbtiny
	-Uflash:w:$PROG_PATH:e
	-v

[env:burn_bootloader_win]
platform_packages = tool_avrdude@symlink://C:/Users/marti/avrdude
platform = atmelavr
board = ATmega328P
upload_protocol = custom
upload_command = avrdude $UPLOAD_FLAGS
upload_flags =
	-pm328pb
	-B10
	-Cavrdude.conf
	-cusbtiny
	-Uflash:w:$PROJECT_DIR/optiboot/optiboot_atmega328.hex:i
	-v

[env:burn_bootloader_fuses_win]
platform_packages = tool_avrdude@symlink://C:/Users/marti/avrdude
platform = atmelavr
board = ATmega328P
upload_protocol = custom
upload_command = avrdude $UPLOAD_FLAGS
upload_flags =
	-pm328pb
	-B10
	-Cavrdude.conf
	-cusbtiny
	-Ulfuse:w:0xEF:m
	-Uhfuse:w:0xDF:m
	-Uefuse:w:0xF7:m
	-Uflash:w:optiboot/optiboot_atmega328.hex:i
	-v

[env:optiboot_win]
platform_packages = tool_avrdude@symlink://C:/Users/marti/avrdude
platform = atmelavr
board = ATmega328P
upload_protocol = custom
upload_command = avrdude $UPLOAD_FLAGS
upload_flags =
	-pm328p
	-Cavrdude.conf
	-carduino
	-PCOM4
	-b19200
	-Uflash:w:$PROG_PATH:e
	-v

[env:USBTiny_fuses_lin]
platform_packages = tool-avrdude@symlink:///home/martin/avrdude
platform = atmelavr
board = ATmega328P
upload_protocol = custom
upload_command = avrdude $UPLOAD_FLAGS
upload_flags =
	-pm328pb
	-B10
	-Cavrdude.conf
	-cusbtiny
	-Ulfuse:w:0xEF:m
	-Uhfuse:w:0xDF:m
	-Uefuse:w:0xF7:m
	-Uflash:w:$PROG_PATH:e
	-v

[env:USBTiny_lin]
platform_packages = tool-avrdude@symlink:///home/martin/avrdude
build_flags = -O3
platform = atmelavr
board = ATmega328P
upload_protocol = custom
upload_command = avrdude $UPLOAD_FLAGS
upload_flags =
	-pm328pb
	-B10
	-Cavrdude.conf
	-cusbtiny
	-Uflash:w:$PROG_PATH:e
	-v

[env:burn_bootloader_lin]
platform_packages = tool-avrdude@symlink:///home/martin/avrdude
platform = atmelavr
board = ATmega328P
upload_protocol = custom
upload_command = avrdude $UPLOAD_FLAGS
upload_flags =
	-pm328pb
	-B10
	-Cavrdude.conf
	-cusbtiny
	-Uflash:w:$PROJECT_DIR/optiboot/optiboot_atmega328.hex:i
	-v

[env:burn_bootloader_fuses_lin]
platform_packages = tool-avrdude@symlink:///home/martin/avrdude
platform = atmelavr
board = ATmega328P
upload_protocol = custom
upload_command = avrdude $UPLOAD_FLAGS
upload_flags =
	-pm328pb
	-B10
	-Cavrdude.conf
	-cusbtiny
	-Ulfuse:w:0xEF:m
	-Uhfuse:w:0xDF:m
	-Uefuse:w:0xF7:m
	-Uflash:w:optiboot/optiboot_atmega328.hex:i
	-v

[env:optiboot_lin]
platform_packages = tool-avrdude@symlink:///home/martin/avrdude
platform = atmelavr
board = ATmega328P
upload_protocol = custom
upload_command = avrdude $UPLOAD_FLAGS
upload_flags =
	-pm328p
	-Cavrdude.conf
	-carduino
	-PCOM4
	-Uflash:w:$PROG_PATH:e
	-v